[project]
name = "amazon-q-match3"
version = "0.1.0"
description = "Match3 puzzle game created with Amazon Q Developer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
]
